AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.3
  Exclude:
    - "vendor/**/*"
    - "pkg/**/*"

Gemspec/DevelopmentDependencies:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 28

Metrics/ClassLength:
  Max: 180

Metrics/MethodLength:
  Max: 20
  Exclude:
    - "test/**/*"

Metrics/ParameterLists:
  CountKeywordArgs: false

Style/Documentation:
  Enabled: false
